Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: presignedUrl.LambdaHandler
      CodeUri: C:\Projetos\Github\hackathon-fiap-presigned-url\HackathonFiapPresignedUrl
      Runtime: java21
      Architectures:
        - x86_64